# Site Configuration
titleBase: thiele.dev
favicon: favicon.ico

# Social media links
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/athiele/
  - name: Email
    url: mailto:alex@thiele.dev
